version: '3'

services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888"
    ports:
      - "12181:12181"
    container_name: zookeeper-1

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888"
    ports:
      - "22181:22181"
    container_name: zookeeper-2

  zookeeper-3:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888"
    ports:
      - "32181:32181"
    container_name: zookeeper-3

  kafka-1:
    image: confluentinc/cp-kafka:5.0.1
    restart: always
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "19092:19092"
    container_name: kafka-1

  kafka-2:
    image: confluentinc/cp-kafka:5.0.1
    restart: always
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "29092:29092"
    container_name: kafka-2

  kafka-3:
    image: confluentinc/cp-kafka:5.0.1
    restart: always
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:22181,zookeeper-3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "39092:39092"
    container_name: kafka-3

  kt-curr-prod-btc:
    build: https://github.com/rafamartinc/kt-currency-producer.git
    image: kt-currency-producer
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      SYMBOL: BTC
      REFERENCE: EUR
      KAFKA_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_TOPIC: kt_currencies
    container_name: kt-curr-prod-btc

  kt-curr-prod-eth:
    image: kt-currency-producer
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      SYMBOL: ETH
      REFERENCE: EUR
      KAFKA_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
      KAFKA_TOPIC: kt_currencies
    container_name: kt-curr-prod-eth

  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
    volumes:
      - /volumes/influxdb/data:/var/lib/influxdb
    container_name: influxdb

  grafana:
    image: grafana/grafana:5.2.4
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana

  kt-curr-live-cons-1:
    build: https://github.com/rafamartinc/kt-currency-live-cons.git
    image: kt-currency-live-cons
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - influxdb
    environment:
      KAFKA_HOST: kafka-1
      KAFKA_PORT: 19092
      KAFKA_TOPIC: kt_currencies
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_DB: currencies
    container_name: kt-currency-live-cons-1

  kt-curr-live-cons-2:
    image: kt-currency-live-cons
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - influxdb
    environment:
      KAFKA_HOST: kafka-1
      KAFKA_PORT: 19092
      KAFKA_TOPIC: kt_currencies
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_DB: currencies
    container_name: kt-currency-live-cons-2

  kt-curr-live-cons-3:
    image: kt-currency-live-cons
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - influxdb
    environment:
      KAFKA_HOST: kafka-1
      KAFKA_PORT: 19092
      KAFKA_TOPIC: kt_currencies
      INFLUX_HOST: influxdb
      INFLUX_PORT: 8086
      INFLUX_DB: currencies
    container_name: kt-currency-live-cons-3

volumes:
  grafana-storage:
