version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    expose:
      - "2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    container_name: kafka

  kt-curr-prod-btc:
    build: ./kt-currency-producer
    image: kt-currency-producer
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      SYMBOL: BTC
      REFERENCE: EUR
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: kt_currencies
    container_name: kt-curr-prod-btc

  kt-curr-prod-eth:
    image: kt-currency-producer
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      SYMBOL: ETH
      REFERENCE: EUR
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: kt_currencies
    container_name: kt-curr-prod-eth